### ISSUE TITLE
`Unable to connect` for Jobs

### ISSUE THREAD

**Issue by lbarcziova** [packit/dashboard#186]
When accessing https://dashboard.packit.dev/jobs, it frequently occurs that `Unable to connect- There was an error retrieving data.` error is displayed.

TODO:
- [ ] investigate what is the reason for this. Suggestions what to check:
    - [ ] memory consumption
    - [ ] possible underlying issue in API responses (some "damaged" record that cannot be parsed and therefore displayed)
- [ ] fix the issue

**Comment by jpopelka** [comment]
If the issue was memory we would most likely see some `process was terminated by signal 9: Killed` in logs (/var/lib/pgsql/data/userdata/log/postgresql-*.log) which is not the case.

I think the [packit-service API queries just take so long](https://github.com/packit/packit-service/issues/1588) that some timeout in the dashboard runs out.
