### ISSUE TITLE
Label groups in tables are not accessiblity friendly

### ISSUE THREAD

**Issue by SpyTec** [packit/dashboard#217]
Within the labels we have groups, such as `Testing Farm`, and within that we have labels that are green or red depending if they passed or not. There is one issue where it seems like screen readers can't read the status of the labels, like `fedora-36-x86_64` saying success, so they have no idea what the current status of it is

What could be used is this, which we can show within each label. E.g. `fedora-36-x86_64 - success`. Where the success part isn't shown visually

https://www.patternfly.org/v4/utilities/accessibility/#screen-reader-only

**Comment by lachmanfrantisek** [comment]
@SpyTec Thanks for the suggestion!

I've checked the link and adding a `<span class="pf-u-screen-reader">` item seems easy to do.

Would you be interested in taking a look at that? Otherwise, someone from the team will take a look...

Also, do you know about anyone using Packit with a screen-reader? (=If we should fix this ASAP..;)

**Comment by SpyTec** [comment]
I'll take a look tomorrow Friday. I don't know of anyone using it with a screen reader, if we did that would be great as we can then improve it a lot better

**Comment by lachmanfrantisek** [comment]
Thanks a lot!
