### ISSUE TITLE
Link to the issues/pull-requests/branches of the repository

### ISSUE THREAD

**Issue by IceWreck** [packit/dashboard#53]
Each git forge has its own url scheme for issues, pull/merge requests and braches. Since we now provide the forge name and other repo details in the API, dashboard should make links according to the respective forge's url scheme.

- /project.../issues
- /project.../releases
- the trigger column in jobs view should link to pull request or branch
- copr link should be moved over to the build id column

**Comment by lachmanfrantisek** [comment]
I'm thinking if you can't use OGR for that:

- github: https://github.com/packit/ogr/blob/462b484164d82822e6ce918292d01772a9eb48a2/ogr/services/github/pull_request.py#L66-L68
- pagure: https://github.com/packit/ogr/blob/462b484164d82822e6ce918292d01772a9eb48a2/ogr/services/pagure/pull_request.py#L68-L77
- gitlab: https://github.com/packit/ogr/blob/462b484164d82822e6ce918292d01772a9eb48a2/ogr/services/gitlab/pull_request.py#L61-L63

(You mostly can't use that without authentication.)

**Comment by IceWreck** [comment]
But then using ogr this will have to be done on the API right? I was thinking of doing this client side. (In JS)
Do we need to provide these links in the API considering it will be redundant info?

**Comment by lachmanfrantisek** [comment]
> But then using ogr this will have to be done on the API right?

If you don't want to have GitHub authentication in the dashboard, then yes. (It will really not be so hard, but we might want to avoid this.)

> I was thinking of doing this client side. (In JS)
> Do we need to provide these links in the API considering it will be redundant info?

We can think about some generic way to to get those values since we might find also other fields that can be easily reached from OGR. (e.g. author of the PR, comments, if it is merged,...) You can also use GitHub without a token, but there is a limit of the number of API calls that is probably not enough.

We can probably enhance the packit-service API so we use the authentication only there. It can only slow the calls since it requires another API calls to GitHub.

We can also save all those values into the database but it will make our database really big.

**Comment by csomh** [comment]
Are these links already available in the payloads based on which the data is created in the database? If yes, it would be probably better to save them in the database and make them available through the API.

This way we wouldn't need to re-compute information which was already made available.

**Comment by IceWreck** [comment]
Cant we hardcode url schemes for forges and make a function to return the correct url? 

Like if forge is github then pull request link will be https://github.com/{namespace}/{repo_name}/pulls/{pr_id} and a similar scheme for gitlab
