### ISSUE TITLE
Never place status/healthcheck inside a project. 

### ISSUE THREAD

**Issue by johannbg** [packit/dashboard#77]
If the dashboard.packit.dev site goes down you cant check the api health status which is like having to walking into a burning building to check if the water flow is OK :smile:  

Place a status page outside the project's infrastructure, which checks for all the relevant stuff and link to that page instead. 
Like for example  [1][2]. 
![Project-Status](https://user-images.githubusercontent.com/1309070/109186756-292d6d80-7789-11eb-8b6d-e88d2a5ce750.png)

1. https://www.githubstatus.com/
2. https://status.fedoraproject.org/

**Comment by lachmanfrantisek** [comment]
Still valid.

**Comment by lachmanfrantisek** [comment]
@johannbg OK, looks like there was no response from our team. Sorry for that.

* This is about API status, not the status of our service -- for the service, we are working on a dedicated webpage at https://github.com/packit/status/
* The dashboard shares the infrastructure with the service.
* Otherwise, the only connection is over the public API of the service.

So, some suggestions:
* Remove the status check entirely as @mfocko suggested => This information is not targeted by the users.
* Replace the info with some warning/error on a page where the API is used.
* Some icon on all pages.
* Any other suggestion?

**Comment by lachmanfrantisek** [comment]
Small update, the dedicated status page is now up: https://status.packit.dev/

**Comment by lachmanfrantisek** [comment]
Today, we agreed on removing this page and linking the https://status.packit.dev/ from the menu instead. The status page does not run in the same infrastructure so we should be safe here.

**Comment by mfocko** [comment]
Closed by #111. Has been changed to link to dedicated status page.
